branch-defaults:
  fx/update_index:
    environment: Technoob-env
environment-defaults:
  Technoob-env:
    branch: dev_server
    repository: origin
global:
  application_name: Technoob
  default_ec2_keyname: project14
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
