name: Client Deployment to Heroku Staging

on:
  push:
    branches:
      - dev_client

defaults:
  run:
    working-directory: Client

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: ""

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: technoob-client-staging
          heroku_email: ooluwatobiiloba@gmail.com

      - name: Restart Dyno
        run: heroku ps:restart --app technoob-client-staging
