name: Build and deploy Node.js project to Azure Function App - NoobscheduledJobs

on:
  push:
    branches:
      - dev_server
  workflow_dispatch:

env:
  NODE_VERSION: '20.x' # Set the desired Node.js version

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: pwsh
        run: |
          pushd .
          cp Function-Worker/package.json package.json
          cp Function-Worker/host.json host.json
          ls
          npm install
          cd Function-Worker/
          npm install
          npm run build --if-present
          npm run test --if-present 
          popd

      - name: Replace main in package.json
        run: |
          # Replace the main value with "Function-Worker/src/functions/*.js" in package.json
          jq '.main = "Function-Worker/src/functions/*.js"' package.json > new_package.json
          cp new_package.json package.json
          rm new_package.json
        working-directory: . 


      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'NoobscheduledJobs'
          slot-name: 'Production'
          package: '.'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_15F8E0BAAF7A44DE9CD7D39C0BE9E50B }}
