name: Client Deployment to Frontend Prod

on:
  push:
    branches:
      - main_client

defaults:
  run:
    working-directory: Client

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          CI: ""
          
      - name: deploy to ec2
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/technoob/
          remote_host: "${{ secrets.CLIENT_EC2_PUBLIC_IP }}"
          remote_user: ubuntu
          remote_key: "${{ secrets.CLIENT_EC2_SSH_PRIVATE_KEY }}"
