name: Delete old artifacts

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Download list of artifacts
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              per_page: 100
            });
            console.log(JSON.stringify(artifacts.data.artifacts));
            return artifacts.data.artifacts;

      - name: Delete old artifacts
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifacts = await github.rest.actions.listArtifactsForRepo({
              per_page: 100
            });
            const threshold = Date.now() - (24 * 60 * 60 * 1000);
            for (const artifact of artifacts.data.artifacts) {
              if (new Date(artifact.created_at) < threshold) {
                console.log(`Deleting artifact ${artifact.name} (${artifact.id})`);
                await github.rest.actions.deleteArtifact({
                  artifact_id: artifact.id
                });
              }
            }
