# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: prod-server-deployment-to-azure-app-service

on:
  push:
    branches:
      - main_server
  workflow_dispatch:

defaults:
  run:
    working-directory: Server
    shell: bash

jobs:
  build-server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm install -g pm2@latest
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r
          ls
          pwd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
            name: node-app
            path: ./Server/release.zip

  deploy-server:
    runs-on: ubuntu-latest
    needs: build-server
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: Server

      - name: unzip artifact for deployment
        run: |
          unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'technoob-staging'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_1ED0C7AB1FD14BCEBAE4D5C3C50431DF }}
          package: .

  deploy-worker-instance:
    runs-on: ubuntu-latest
    needs: build-server

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: |
          npm install
          npm run test --if-present


      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: technoob-worker
          heroku_email: ooluwatobiiloba@gmail.com
          buildpack: 'heroku/nodejs'
          branch: main_server
          app_dir: '.'

      - name: Restart Dyno
        run: heroku ps:restart --app technoob-worker

      - name: Install Pupetter globally
        run: npm install -g puppeteer

      - name: Install Packages
        run: npm install

      - name: Start worker instance
        run: heroku ps:scale worker=1 --app technoob-worker

  deploy-cron-worker-instance:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push to DockerHub
        run: |
          ls
          docker build --platform linux/amd64 -t oluwatobiiloba/function-worker:latest .
          docker push oluwatobiiloba/function-worker:latest
        working-directory: Function-Worker-2.0





