name: SSH into webapp and run command
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure CLI action
      uses: azure/cli@v1.0.0
      with:
        inlineScript: |
          az webapp ssh -g Technoob -n technoob-staging
          # Run your command here
          whoami
